// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// a_opt_trace
NumericVector a_opt_trace(const arma::mat& X_now, const arma::mat& X_new, const arma::vec& w_now, const arma::vec& w_new);
RcppExport SEXP _DistrSeqEst_a_opt_trace(SEXP X_nowSEXP, SEXP X_newSEXP, SEXP w_nowSEXP, SEXP w_newSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_now(X_nowSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_new(X_newSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_now(w_nowSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w_new(w_newSEXP);
    rcpp_result_gen = Rcpp::wrap(a_opt_trace(X_now, X_new, w_now, w_new));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DistrSeqEst_a_opt_trace", (DL_FUNC) &_DistrSeqEst_a_opt_trace, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_DistrSeqEst(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
