# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

a_opt_trace <- function(X_now, X_new, w_now, w_new) {
    .Call(`_DistrSeqEst_a_opt_trace`, X_now, X_new, w_now, w_new)
}

